spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/gbpark
    username : gbpark
    password :
    driver-class-name : org.h2.Driver

  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false

  jpa:
    hibernate:
      ddl-auto : create
    properties:
      hibernate:
        format_sql : true
    open-in-view: false

  devtools:
    livereload:
      enabled: true

logging:
  level:
    org.hibernate.SQL : debug
    root : warn
    #parameter 표시
    #org.hibernate.type : trace
